"""Audit Pydantic Schemas."""

import uuid
from datetime import datetime
from typing import Any
from pydantic import BaseModel, Field


class FindingResponse(BaseModel):
    id: uuid.UUID
    control_id: str
    framework: str
    severity: str
    finding_title: str
    finding_description: str
    device_rule_reference: str | None = None
    remediation: str | None = None
    citation_source: str
    citation_section: str | None = None
    citation_url: str | None = None
    citation_page: int | None = None
    confidence_score: float = 1.0

    class Config:
        from_attributes = True


class FindingSchema(BaseModel):
    """Schema for individual findings generated by LLM reasoning."""
    control_id: str = Field(..., description="Framework control ID, e.g. AC-4")
    framework: str = Field(..., description="Framework name, e.g. NIST_800_53_R5")
    severity: str = Field(..., description="Critical, High, Medium, Low")
    finding_title: str = Field(..., description="Concise title of the non-compliance finding")
    finding_description: str = Field(..., description="Detailed description of the violation")
    device_rule_reference: str = Field(..., description="Device configuration rule line or identifier")
    remediation: str = Field(..., description="Actionable remediation steps")
    citation_source: str = Field(..., description="Exact framework publication name")
    citation_section: str = Field(..., description="Section / requirement clause number")
    citation_url: str | None = Field(default=None, description="Official reference URL")
    citation_page: int | None = Field(default=None, description="Page number in standard PDF")
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0)


class AuditSummary(BaseModel):
    total_findings: int = 0
    critical_count: int = 0
    high_count: int = 0
    medium_count: int = 0
    low_count: int = 0
    compliance_score_percent: float = 100.0


class AuditResponse(BaseModel):
    """Structured LLM Audit reasoning output."""
    findings: list[FindingSchema] = Field(default_factory=list)
    summary: AuditSummary = Field(default_factory=AuditSummary)


class AuditCreateRequest(BaseModel):
    device_config_id: uuid.UUID
    frameworks: list[str] = Field(
        default=["NIST_800_53_R5"],
        description="Frameworks to audit against (e.g. NIST_800_53_R5, CIS_v8, ISO27001_2022, PCI_DSS_4.0)",
    )


class AuditCreateResponse(BaseModel):
    audit_job_id: uuid.UUID
    status: str
    estimated_time_seconds: int = 30
    message: str = "Audit job successfully queued"


class AuditJobResponse(BaseModel):
    id: uuid.UUID
    device_config_id: uuid.UUID
    framework_filter: list[str]
    status: str
    started_at: datetime
    completed_at: datetime | None = None
    total_findings: int = 0
    critical_count: int = 0
    high_count: int = 0
    medium_count: int = 0
    low_count: int = 0
    compliance_score_percent: float = 100.0
    findings: list[FindingResponse] = Field(default_factory=list)

    class Config:
        from_attributes = True


class CitationCardModel(BaseModel):
    control_id: str
    framework: str
    title: str
    citation_source: str
    citation_section: str | None = None
    citation_page: int | None = None
    citation_url: str | None = None
    confidence: float = 1.0


class ComplianceQueryRequest(BaseModel):
    query: str = Field(..., min_length=3, max_length=1000, description="Natural language compliance query")
    framework: str | None = Field(default=None, description="Optional framework filter")
    top_k: int = Field(default=5, ge=1, le=20)


class ComplianceQueryResponse(BaseModel):
    query: str
    answer: str
    sources: list[CitationCardModel] = Field(default_factory=list)
    confidence: float = 1.0
